### ISSUE TITLE
`Unexpected compiler response: {:error, %CompileError{...}}`

### ISSUE THREAD

**Issue by petermueller** [elixir-tools/next-ls#284] opened 2023-10-12 16:04 UTC
NextLS Version: 0.13.4, from `brew`
Transport: TCP
Editor + Version: VSCode, 1.83.1
Elixir Version: 1.13.4 (set globally w/ ASDF as `1.13.4-otp-25`)
Erlang/OTP Version: 25.2.3 (set globally w/ ASDF as `25.2.3`)
macOS Version + arch: 13.5.2 (Ventura), Intel x86

I'm seeing a compile error related to a private repo dep we have when I open an elixir file for our application

From the logs it seems like it's ***not because*** it's private, but just that it's the first dep that is being compiled.

Above the error listed below, I'm seeing tons of `run mix deps.get` style warnings for standard hex.pm hosted packages too, and I'm positive that my deps are pulled down for the proper version.

I'm also seeing the typical "(Mix) Can't continue due to errors on dependencies", followed by a node down crash 

I'm starting vscode from the command line, and have confirmed that `asdf` is setting Elixir to the same version as my `asdf local`, just in case maybe `nextls` was calling `elixir` from its own directory, or the directory I was running it in (same as the app), and potentially getting missing deps.

```
[NextLS] ==> my_priv_gh_repo
Error while loading project :my_priv_gh_repo at /Users/peter/code/my_app/deps/my_priv_gh_repo
[Trace - 10:46:51 AM] Received notification 'window/logMessage'.
[Warn  - 10:46:51 AM] [NextLS] Unexpected compiler response: {:error, %CompileError{file: "/Users/peter/code/my_app/deps/my_priv_gh_repo/mix.exs", line: 1, description: "cannot define module MyPrivGhRepo.MixProject because it is currently being defined in /Users/peter/code/my_app/deps/my_priv_gh_repo/mix.exs:1"}}
[Trace - 10:46:51 AM] Received notification '$/progress'.
```

after enabling verbose, clearing `./.elixir-tools/` and rerunning a little later:

```
[NextLS] Error while loading project :my_priv_gh_repo at /Users/peter/code/my_app/deps/my_priv_gh_repo
[Trace - 11:41:49 AM] Received notification 'window/logMessage'.
Params: {
    "message": "[NextLS] Unexpected compiler response: {:error, %CompileError{file: \"/Users/peter/code/my_app/deps/my_priv_gh_repo/mix.exs\", line: 1, description: \"cannot define module MyPrivGhRepo.MixProject because it is currently being defined in /Users/peter/code/my_app/deps/my_priv_gh_repo/mix.exs:1\"}}",
    "type": 2
}
```

If I switch to 1.14+ for `asdf global` and load up fresh phx.new everything seems to work fine.

**Comment by mhanberg** [comment] 2023-10-12 16:18
Public repo reproducing the issue is always helpful! 

See you next week 😎

**Comment by mhanberg** [comment] 2023-10-16 16:30
I'm back from vacation, will hopefully take a look umbrella app in Zed this week.

If you do get time tho, a repro would be helpful, but now worries if you're busy

**Comment by mhanberg** [comment] 2023-10-17 03:06
> I'm back from vacation, will hopefully take a look umbrella app in Zed this week.

I think I got my wires crossed with a different issue 😅

**Comment by slashmili** [comment] 2024-03-04 10:19
Update: I've upgraded to `Next LS v0.19.1` and use the same `nvim-lspconfig` as before and still get this : 
```
Unexpected compiler response: {:error, %CompileError{file: "/Users/milad/dev/my_app/deps/ecto/mix.exs", line: 0, description: "cannot compile module Ecto.MixProject (errors have been logged)"}}'
```

**Comment by mhanberg** [comment] 2024-03-04 13:46
@slashmili I don't recommend swapping nextls into the elixirls lsp config config. 

Can you try with the official elixir-tools.nvim plugin?

**Comment by mhanberg** [comment] 2024-03-04 14:00
With regard to the original issue, I recommend trying again with the latest, as there is functionality to handle the dependency issues

**Comment by slashmili** [comment] 2024-03-06 14:42
You are correct! sorry for my mistake. I didn't pay attention. As of using `elixir-tools.nvim`, it's an option but I'd rather to keep my dependencies bear minimum. I'll try to extract the `next-ls` config from `elixir-tools.nvim`.

From my POV you may close the issue!

**Comment by mhanberg** [comment] 2024-03-27 19:08
I believe https://github.com/elixir-tools/next-ls/pull/401 should close out this issue, I will likely release it in v0.20.2, please update and let me know if you can still reproduce.

I'll close the issue if I don't hear back in a while, but feel free to comment and I'll re-open

**Closed** 2024-04-01 15:30 UTC
