### ISSUE TITLE
VSCode save takes a lot of time

### ISSUE THREAD

**Issue by cvkmohan** [elixir-tools/next-ls#392] opened 2024-03-10 15:21 UTC
![image](https://github.com/elixir-tools/next-ls/assets/3105388/a8fa1cf5-1cf5-4774-8d83-214ab48fae70)
I have `formatonsave` on in vscode. Now, it is taking a long time - sometimes upto a minute or more. It was not the case earlier.

**Comment by mhanberg** [comment] 2024-03-10 15:42
Can you check the output panel for errors

**Comment by cvkmohan** [comment] 2024-03-10 16:08
![image](https://github.com/elixir-tools/next-ls/assets/3105388/e5bec317-a987-4a80-9c5e-01e7ab08bbc2)
Could not find any errors. This is the message I am getting when I changed the setting to `verbose` on server communication

**Comment by mhanberg** [comment] 2024-03-10 16:36
gotcha, there must be something weird with formatting

I don't think i've personally attempted to save a heex file (i use the sigil), i'll attempt to reproduce

**Comment by rdlu** [comment] 2024-03-11 13:15
I have something related. I just updated nextls, but I'm using neovim. 

Heex files sometimes takes a long time, but after a while they become instantly formatted, and some times I'm under impression that it's not triggering at at all. 

At the first save it consumes a lot of cpu and I can listen the fan blowing hard for a few to several seconds, but I was not able to pinpoint anything using btop.

I did `Elixir nextls uninstall` and it improved after reinstalling, even with the auto update telling me it was successful.

Thanks for your efforts! Since last week I using nextls, including completion. I must say it's more stable than using the old lsp, like in presence of errors and crashing with incomplete code.

Let me know if you need any extra logs, looking at first glance it doesn't look like I have any errors on it as well.

The only strange things I seeing are from other tools, like `tail`:

`tail: inotify cannot be used, reverting to polling: Too many open files` even with `fs.inotify.max_user_watches = 524288`

**Comment by mhanberg** [comment] 2024-03-11 16:03
Please check the log file at .elixir-tools/nextls.log

**Comment by mhanberg** [comment] 2024-03-11 16:04
The log you shared is from ElixirLS, not Next LS. Please make sure you are only using one and try to reproduce again.

**Comment by rdlu** [comment] 2024-03-12 10:38
(op: sorry for stealing a vscode thread)

I did not found this log file. My neovim lsp info is apparently merging all lsp related logs are inside ` ~/.local/state/nvim/lsp.log`. 

Using `find . -name nextls.log` from my home folder is yielding 0 results.

```
Language client log: /home/rdlu/.local/state/nvim/lsp.log
 Detected filetype:   elixir
....

Client: elixirls (id: 3, bufnr: [3])
 	filetypes:       elixir, eelixir, heex, surface
 	autostart:       true
 	root directory:  /home/rdlu/Projects/test
 	cmd:             elixir-ls
 
 Client: Next LS (id: 5, bufnr: [3])
 	filetypes:       
 	autostart:       false
 	root directory:  Running in single file mode.
 	cmd:             /home/rdlu/.cache/elixir-tools/nextls/bin/nextls --stdio

```

But you're right, even with elixirls disabled, removing references from Mason, lazyvim extras, etc, the lsp info is saying that elixirls is still running:

`~/.config/nvim/lua/plugins/elixir.lua`

```
....
        elixirls = {
          enable = false,
        },
...
```

I'll try to open an issue on elixir-tools.nvim instead and keep observing the logs.

Thanks!

**Comment by cvkmohan** [comment] 2024-03-27 13:36
This problem is persisting. 
![image](https://github.com/elixir-tools/next-ls/assets/3105388/be18f121-e239-42dd-9e3d-5199eb1ceea4)
This is all that I can see in the log. But, it is taking a long time to save. 
I wanted to report because, this is a fresh installation. WSL, Ubuntu 22.04, asdf, elixir - everything freshly installed.

**Comment by mhanberg** [comment] 2024-03-27 19:07
I believe https://github.com/elixir-tools/next-ls/pull/401 should close out this issue, I will likely release it in v0.20.2, please update and let me know if you can still reproduce.

I'll close the issue if I don't hear back in a while, but feel free to comment and I'll re-open

**Closed** 2024-04-01 15:30 UTC
